CREATE TABLE [dbo].[MediaHistory]
(
	HistoryID INT PRIMARY KEY IDENTITY(1, 1),
    MediaID INT NOT NULL,
    UniqueID NVARCHAR(40) NOT NULL, 
    Name NVARCHAR(255) NOT NULL,
    MIMEType NVARCHAR (50) NOT NULL,
    Path NVARCHAR(MAX) NOT NULL,
    Extension NVARCHAR(20) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CreatedBy NVARCHAR(40) NOT NULL,
    LastModifiedAt DATETIMEOFFSET NOT NULL,
    LastModifiedBy NVARCHAR(40) NOT NULL,
    IsArchived BIT NOT NULL,
    IsActive BIT NOT NULL,
    Operation NVARCHAR(6) NOT NULL,
    ChangeTimestamp DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
)
