CREATE TABLE [dbo].[Media]
(
	ID INT PRIMARY KEY IDENTITY(1, 1),
    UniqueID NVARCHAR(40) NOT NULL UNIQUE, 
    Name NVARCHAR(255) NOT NULL,
    MIMEType NVARCHAR (50) NOT NULL,
    Path NVARCHAR(MAX) NOT NULL,
    Extension NVARCHAR(20) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CreatedBy NVARCHAR(40) NOT NULL,
    LastModifiedAt DATETIMEOFFSET NOT NULL,
    LastModifiedBy NVARCHAR(40) NOT NULL,
    IsArchived BIT NOT NULL,
    IsActive BIT NOT NULL
);

GO

CREATE UNIQUE INDEX IX_Media_UniqueID ON Media(UniqueID);