CREATE TABLE [dbo].[OAuthAuthorizationCodes]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [UniqueID] VARCHAR(40) NOT NULL,
    [UserID] INT NOT NULL,
    [ClientID] INT NOT NULL,
    [Code] NVARCHAR(256) UNIQUE NOT NULL,
    [Expiry] DATETIME2 NOT NULL,
    FOREIGN KEY (UserID) REFERENCES Users(ID),
    FOREIGN KEY (ClientID) REFERENCES OAuthClients(ID),
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END,
    PERIOD FOR SYSTEM_TIME([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OAuthAuthorizationCodesHistory], DATA_CONSISTENCY_CHECK = ON))