CREATE TABLE [dbo].[OAuthClients]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1, 1),
    [UniqueID] NVARCHAR(40) UNIQUE NOT NULL,
    [Name] NVARCHAR(256) NOT NULL,
    [ClientID] NVARCHAR(256) UNIQUE NOT NULL,
    [ClientSecret] NVARCHAR(256) NOT NULL,
    [RedirectUri] NVARCHAR(512) NOT NULL,
    [CreatedAt] DATETIMEOFFSET NOT NULL,
    [CreatedBy] NVARCHAR(40) NOT NULL,
    [LastModifiedAt] DATETIMEOFFSET NOT NULL,
    [LastModifiedBy] NVARCHAR(40) NOT NULL,
    [IsArchived] BIT NOT NULL,
    [IsActive] BIT NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END,
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = [dbo].[OAuthClientsHistory], DATA_CONSISTENCY_CHECK = ON))