CREATE TABLE [dbo].[Plot]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Plot_FileID] INT REFERENCES Files([ID]),
    [UniqueID] NVARCHAR(40) NOT NULL UNIQUE, 
    [Name] NVARCHAR(256) NOT NULL,
    [Description] NVARCHAR(MAX) NULL,
    [DisplayOrder] INT NOT NULL,
    [CreatedAt] DATETIMEOFFSET NOT NULL,
    [CreatedBy] NVARCHAR(40) NOT NULL,
    [LastModifiedAt] DATETIMEOFFSET NOT NULL,
    [LastModifiedBy] NVARCHAR(40) NOT NULL,
    [IsArchived] BIT NOT NULL,
    [IsActive] BIT NOT NULL,
    [ValidFrom] DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo] DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
    PERIOD FOR SYSTEM_TIME([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON(HISTORY_TABLE = [dbo].[PlotsHistory], DATA_CONSISTENCY_CHECK = ON));

GO

CREATE UNIQUE INDEX IX_Plot_UniqueID ON Plot([UniqueID]);